apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-networking
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/arielpacciaroni/k8s-networking.git
    targetRevision: HEAD
    path: deployment/base
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-networking # Namespace for the application

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true