apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- microservice-auth-deployment.yaml
- microservice-auth-service.yaml
- microservice-frontend-deployment.yaml
- microservice-frontend-service.yaml
# - ingress-nginx.yaml
images:
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-auth
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-auth
  newTag: d64a17d84657e8aa60ed3518e638b48b67f27e32
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-frontend
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-frontend
  newTag: d64a17d84657e8aa60ed3518e638b48b67f27e32
