apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- microservice-auth-deployment.yaml
- microservice-auth-service.yaml
- microservice-frontend-deployment.yaml
- microservice-frontend-service.yaml
- ingress.yaml
images:
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-auth
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-auth
  newTag: 145822d4ece620933355a2e156f2f78d52320a89
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-frontend
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-frontend
  newTag: 145822d4ece620933355a2e156f2f78d52320a89
