apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- microservice-auth-deployment.yaml
- microservice-auth-service.yaml
- microservice-frontend-deployment.yaml
- microservice-frontend-service.yaml
- ingress.yaml
images:
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-auth
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-auth
  newTag: 96caf837ad1d032bc4625e36b15837db82fd6ec5
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-frontend
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-frontend
  newTag: 96caf837ad1d032bc4625e36b15837db82fd6ec5
