apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- microservice-auth-deployment.yaml
- microservice-auth-service.yaml
- microservice-frontend-deployment.yaml
- microservice-frontend-service.yaml
- ingress-nginx.yaml
images:
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-auth
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-auth
  newTag: 22452f43babe78c0a7869b1cd03591d6a6cb028c
- name: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-frontend
  newName: 091733698341.dkr.ecr.us-east-1.amazonaws.com/microservice-frontend
  newTag: 22452f43babe78c0a7869b1cd03591d6a6cb028c
