apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler

metadata:
 name: auth-hpa

spec:
  scaleTargetRef:
    name: auth-deployment

  minReplicas: 1
  maxReplicas: 3

  metrics:
  - type: Resource
    resource:
    name: cpu
    target:
      type: Utilization
      averageUtilization: 60
