apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app.kubernetes.io/name: auth-service
spec:
  selector:
    app.kubernetes.io/name: auth
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003